### ISSUE TITLE
How to post diffrent data?

### ISSUE THREAD

**Issue by bamboo-cp3** [nakabonne/ali#91]
`ali -H "Accept: application/json" -H "Content-type: application/json" \
-m "POST" \
-b '{"name":"xxx"}'`

now i want to send some diffrent data peer request, What shall I do?

**Comment by nakabonne** [comment]
@bamboo-cp3 Hi, tell me a little bit about what you want to do. Does it mean you want to send different content as a request body for each request?

**Comment by nakabonne** [comment]
Close for now. Feel free to re-open if you're still facing this issue.

**Comment by Dgame** [comment]
I would actually want this too. So that I have not the same Requests every time so that the response might differ and I really have a stress test like it would be if different users would use my API. Is this possible? Maybe a simplified version of this https://github.com/americanexpress/baton#requests-file
